### ISSUE TITLE
Use a cache to speed up testing on the second launch.

### ISSUE THREAD

**Issue by sfonteneau** [ChouaibKhamallah/SambaADAuditPasswords#1]
To speed up the verification on the second launch, we could save a cache of hashes with their results. If the last violation (ModifiedDate) has changed date then we purge the cache

**Comment by ChouaibKhamallah** [comment]
The modifications were made to provide this improvement

https://github.com/ChouaibKhamallah/SambaADAuditPasswords/commit/36e25f1fdf61c4fcafa6501abb5162bfb3d9eada
