### ISSUE TITLE
 Small typo

### ISSUE THREAD

**Issue by Stricken1670** [ChouaibKhamallah/SambaADAuditPasswords#2]
Dear @ChouaibKhamallah 

Your program contains a small typo. The correct spelling would be "privileged". 

BR

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
PR opened @ChouaibKhamallah @Stricken1670

**Comment by ChouaibKhamallah** [comment]
Thx, fix commited

**Comment by ChouaibKhamallah** [comment]
Closed
